name: Build and commit dist on Dependabot PR

on:
    push:
        branches:
            - dependabot/**

jobs:
    build-and-commit:
        runs-on: warp-ubuntu-latest-x64-2x
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  persist-credentials: true # so we can push
                  fetch-depth: 0 # get all commits and tags
                  fetch-tags: true # ensure tags are fetched too
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
            - name: Build
              env:
                  CI: "" # empty string → falsy in JS
                  GITHUB_ACTIONS: ""
              run: |
                  npm install --include=dev
                  npm run build
            - name: Create GitHub App Token
              uses: actions/create-github-app-token@v1
              id: app-token
              with:
                  app-id: ${{ vars.WARPERBOT_APP_ID }}
                  private-key: ${{ secrets.WARPERBOT_PRIVATE_KEY }}
                  repositories: "cache"
            # - uses: mxschmitt/action-tmate@v3
            - name: Commit updated dist
              env:
                  WARPERBOT_SLUG: ${{ vars.WARPERBOT_SLUG }}
                  WARPERBOT_EMAIL: ${{ vars.WARPERBOT_EMAIL }}
                  GH_TOKEN: ${{ steps.app-token.outputs.token }}
              run: |
                  git config --global user.name "$WARPERBOT_SLUG[bot]"
                  git config --global user.email "$WARPERBOT_EMAIL"
                  git remote set-url origin $(git config remote.origin.url | sed "s/github.com/${WARPERBOT_SLUG}:${GH_TOKEN}@github.com/g")
                  git add .
                  git commit -m "build: update dist" || true
                  git push
