name: Docker Layer Caching Test

on:
  push:
    branches:
      - dlc-test

# env:
#   WARPBUILD_CACHE_URL: "https://1d2d-2401-4900-1c43-6e65-b878-8aaf-f339-7641.ngrok-free.app"

jobs:
  test-docker-layer-caching:
    strategy:
      matrix:
        os: [warp-ubuntu-latest-x64-4x]
        # os: [warpdev-ubuntu-latest-x64-4x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
      - name: Build Docker Image at projects/Dockerfile using build push action
        uses: docker/build-push-action@v6
        with:
          context: .github/tests/dockerfile-cache
          file: .github/tests/dockerfile-cache/Dockerfile
          push: false
          tags: warpbuilds/warp-cache-simulator:latest
          cache-from: type=gha,url=http://127.0.0.1:49160/
          cache-to: type=gha,url=http://127.0.0.1:49160/,mode=max