name: Performance Test WarpCache

on:
  push:
    branches:
      - main
      - prajjwal-warp-245

env:
  WARPBUILD_CACHE_URL: 'https://cache.dev.warpbuild.dev'

jobs:
  perf-test:
    strategy:
      matrix:
        os: [warpdev-ubuntu-latest-x64-4x, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create a temp directory
      run: mkdir -p temp
    - name: Generate 500MB data from urandom
      run: dd if=/dev/urandom of=temp/1GB bs=1M count=5000
    - name: WarpCache
      if: matrix.os == 'warpdev-ubuntu-latest-x64-4x'
      uses: WarpBuilds/cache@v1.0.9-beta
      with:
        path: temp/
        key: test-5GB
    - name: Cache
      if: matrix.os == 'ubuntu-latest'
      uses: actions/cache@v4.0.2
      with:
        path: temp/
        key: test-5GB