name: WarpCache Run Test

on:
  push:
    branches:
      - perf-test-warpcache
  workflow_dispatch:

jobs:
  perf-test:
    strategy:
      matrix:
        os: [warp-ubuntu-latest-x64-4x, ubuntu-latest]
        # Size is given in MB
        size: [500]
        # Use run to test single job performance across multiple runs
        # run: [10, 20, 30, 40, 50, 60, 70, 80, 90]
        # Use jobs to test multiple concurrent jobs performance
        jobs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create a temp directory
        run: mkdir -p temp
      - name: Generate ${{matrix.size}}MB data from urandom
        run: dd if=/dev/urandom of=temp/500MB bs=1M count=${{ matrix.size }}
      # Use this to test single concurrent job performance
      # - name: Sleep
      #   run: sleep ${{ matrix.run }}
      - name: WarpCache
        if: matrix.os == 'warp-ubuntu-latest-x64-4x'
        uses: WarpBuilds/cache@v1
        with:
          path: temp/
          key: perf-test-${{ matrix.size }}MB-10s
      - name: Cache
        if: matrix.os == 'ubuntu-latest'
        uses: actions/cache@v4.0.2
        with:
          path: temp/
          key: perf-test-${{ matrix.size }}MB-10s

  calculate-median:
    runs-on: warp-ubuntu-latest-x64-4x
    needs: perf-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: |
          npm install @octokit/rest

      - name: Calculate median runtime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/calculate_median.js