name: WarpCache Run Test

on:
  push:
    branches:
      - perf-test-warpcache
  workflow_dispatch:

jobs:
  perf-test:
    strategy:
      matrix:
        os: [warp-ubuntu-latest-x64-4x, ubuntu-latest]
        size: [500]
        run: [10, 20]
        # jobs: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create a temp directory
        run: mkdir -p temp
      - name: Generate ${{matrix.size}}MB data from urandom
        run: dd if=/dev/urandom of=temp/500MB bs=1M count=${{ matrix.size }}
      # - name: Sleep
      #   run: sleep ${{ matrix.run }}
      - name: WarpCache
        if: matrix.os == 'warp-ubuntu-latest-x64-4x'
        uses: WarpBuilds/cache@v1
        with:
          path: temp/
          key: perf-test-${{ matrix.size }}MB-10s
      - name: Cache
        if: matrix.os == 'ubuntu-latest'
        uses: actions/cache@v4.0.2
        with:
          path: temp/
          key: perf-test-${{ matrix.size }}MB-10s

  calculate-median:
    runs-on: warp-ubuntu-latest-x64-4x
    needs: perf-test # Ensure this runs after perf-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: |
          npm install @octokit/rest

      - name: Calculate median runtime
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/calculate_median.js